style: fix styling on some files

diff --git a/home/dot_local/bin/executable_styled b/home/dot_local/bin/executable_styled
--- a/home/dot_local/bin/executable_styled
+++ b/home/dot_local/bin/executable_styled
@@ -46,96 +46,96 @@ parse_commandline() {
   while test $# -gt 0; do
     _key="$1"
     case "$_key" in
-    -b | --no-bold | --bold)
-      _arg_bold="on"
-      test "${1:0:5}" = "--no-" && _arg_bold="off"
-      ;;
-    -b*)
-      _arg_bold="on"
-      _next="${_key##-b}"
-      if test -n "$_next" -a "$_next" != "$_key"; then
-        { begins_with_short_option "$_next" && shift && set -- "-b" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-      fi
-      ;;
-    -d | --no-dim | --dim)
-      _arg_dim="on"
-      test "${1:0:5}" = "--no-" && _arg_dim="off"
-      ;;
-    -d*)
-      _arg_dim="on"
-      _next="${_key##-d}"
-      if test -n "$_next" -a "$_next" != "$_key"; then
-        { begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-      fi
-      ;;
-    -u | --no-underline | --underline)
-      _arg_underline="on"
-      test "${1:0:5}" = "--no-" && _arg_underline="off"
-      ;;
-    -u*)
-      _arg_underline="on"
-      _next="${_key##-u}"
-      if test -n "$_next" -a "$_next" != "$_key"; then
-        { begins_with_short_option "$_next" && shift && set -- "-u" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-      fi
-      ;;
-    -i | --no-italic | --italic)
-      _arg_italic="on"
-      test "${1:0:5}" = "--no-" && _arg_italic="off"
-      ;;
-    -i*)
-      _arg_italic="on"
-      _next="${_key##-i}"
-      if test -n "$_next" -a "$_next" != "$_key"; then
-        { begins_with_short_option "$_next" && shift && set -- "-i" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-      fi
-      ;;
-    -k | --no-blink | --blink)
-      _arg_blink="on"
-      test "${1:0:5}" = "--no-" && _arg_blink="off"
-      ;;
-    -k*)
-      _arg_blink="on"
-      _next="${_key##-k}"
-      if test -n "$_next" -a "$_next" != "$_key"; then
-        { begins_with_short_option "$_next" && shift && set -- "-k" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-      fi
-      ;;
-    -g | --background)
-      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-      _arg_background="$2"
-      shift
-      ;;
-    --background=*)
-      _arg_background="${_key##--background=}"
-      ;;
-    -g*)
-      _arg_background="${_key##-g}"
-      ;;
-    -c | --color)
-      test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-      _arg_color="$2"
-      shift
-      ;;
-    --color=*)
-      _arg_color="${_key##--color=}"
-      ;;
-    -c*)
-      _arg_color="${_key##-c}"
-      ;;
-    -h | --help)
-      print_help
-      exit 0
-      ;;
-    -h*)
-      print_help
-      exit 0
-      ;;
-    *)
-      _last_positional="$1"
-      _positionals+=("$_last_positional")
-      _positionals_count=$((_positionals_count + 1))
-      ;;
+      -b | --no-bold | --bold)
+        _arg_bold="on"
+        test "${1:0:5}" = "--no-" && _arg_bold="off"
+        ;;
+      -b*)
+        _arg_bold="on"
+        _next="${_key##-b}"
+        if test -n "$_next" -a "$_next" != "$_key"; then
+          { begins_with_short_option "$_next" && shift && set -- "-b" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+        fi
+        ;;
+      -d | --no-dim | --dim)
+        _arg_dim="on"
+        test "${1:0:5}" = "--no-" && _arg_dim="off"
+        ;;
+      -d*)
+        _arg_dim="on"
+        _next="${_key##-d}"
+        if test -n "$_next" -a "$_next" != "$_key"; then
+          { begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+        fi
+        ;;
+      -u | --no-underline | --underline)
+        _arg_underline="on"
+        test "${1:0:5}" = "--no-" && _arg_underline="off"
+        ;;
+      -u*)
+        _arg_underline="on"
+        _next="${_key##-u}"
+        if test -n "$_next" -a "$_next" != "$_key"; then
+          { begins_with_short_option "$_next" && shift && set -- "-u" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+        fi
+        ;;
+      -i | --no-italic | --italic)
+        _arg_italic="on"
+        test "${1:0:5}" = "--no-" && _arg_italic="off"
+        ;;
+      -i*)
+        _arg_italic="on"
+        _next="${_key##-i}"
+        if test -n "$_next" -a "$_next" != "$_key"; then
+          { begins_with_short_option "$_next" && shift && set -- "-i" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+        fi
+        ;;
+      -k | --no-blink | --blink)
+        _arg_blink="on"
+        test "${1:0:5}" = "--no-" && _arg_blink="off"
+        ;;
+      -k*)
+        _arg_blink="on"
+        _next="${_key##-k}"
+        if test -n "$_next" -a "$_next" != "$_key"; then
+          { begins_with_short_option "$_next" && shift && set -- "-k" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+        fi
+        ;;
+      -g | --background)
+        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+        _arg_background="$2"
+        shift
+        ;;
+      --background=*)
+        _arg_background="${_key##--background=}"
+        ;;
+      -g*)
+        _arg_background="${_key##-g}"
+        ;;
+      -c | --color)
+        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+        _arg_color="$2"
+        shift
+        ;;
+      --color=*)
+        _arg_color="${_key##--color=}"
+        ;;
+      -c*)
+        _arg_color="${_key##-c}"
+        ;;
+      -h | --help)
+        print_help
+        exit 0
+        ;;
+      -h*)
+        print_help
+        exit 0
+        ;;
+      *)
+        _last_positional="$1"
+        _positionals+=("$_last_positional")
+        _positionals_count=$((_positionals_count + 1))
+        ;;
     esac
     shift
   done
